#ifndef _EARTHLINGS_H
#define _EARTHLINGS_H

#define EARTHLING_SHIP_PIECE		0x00
#define EARTHLING_DEVIL			0x01
#define EARTHLING_HAMSTER		0x02
#define EARTHLING_SHOPPING_CART		0x03
#define EARTHLING_DENTIST		0x04
#define EARTHLING_WAHINI		0x05
#define EARTHLING_BEES			0x06
#define EARTHLING_CUPID			0x07
#define EARTHLING_TORNADO		0x08
#define EARTHLING_MAILBOX		0x09
#define EARTHLING_WIZARD		0x0A
#define EARTHLING_WISEMAN		0x0B
#define EARTHLING_NERDS			0x0C
#define EARTHLING_LAWNMOWER_MAN		0x0D
#define EARTHLING_SHARK			0x0E
#define EARTHLING_CHICKENS		0x0F
#define EARTHLING_BOOGIE		0x10
#define EARTHLING_OPERA_SINGER		0x11
#define EARTHLING_MOLE			0x12
#define EARTHLING_ICE_CREAM_TRUCK	0x13
#define EARTHLING_SANTA			0x14
#define EARTHLING_ANGRY_DENTIST		0x15
#define EARTHLING_ANGRY_BEES		0x16
#define EARTHLING_LEMONADE_STAND	0x17
#define EARTHLING_HOTTUB		0x18
#define EARTHLING_NONE			0xFF

#endif
