#!/usr/bin/env python3
# pulls comment blocks out of the asm so that they can be used in a C
# header file.

import argparse
import os
from collections import namedtuple

parser = argparse.ArgumentParser(description='Header generator')
parser.add_argument('asmfile', help='Source ASM')
args = vars(parser.parse_args())

print("/*")
print(" * prototype declarations")
print(" * this file is automatically generated")
print(" */")
print()
print("#pragma once")
print()

with open(args['asmfile'], "r") as asm:
    while True:
        line = asm.readline()
        if not line:
            break

        if line.startswith(";; "):
            print(line[3:len(line)-1])

